### PR TITLE
Style updates and minor markup changes

### PR DESCRIPTION
**Pull request by sg00dwin**
@stevekuznetsov updates

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why is the diff so large? I want something small that we can go upstream and say -- this is what we did

**Comment by sg00dwin** [comment]
@stevekuznetsov ah, didn't know this was going upstream. I included all our styles at the bottom to override some of their's.

I'll pull together what can be submitted upstream and separate out Origin specific branding.

**Comment by sg00dwin** [comment]
@stevekuznetsov please pull these in and update https://v20170913-1055b3e-dot-openshift-gce-devel.appspot.com/ 

or you can update a new instance where style.css matches upstream.

style.css contains things that can go upstream
openshift.css contains custom branding for us

Notable:
Build list are consistent widths for better readability
Mobile support
- header, lists causing horizontal scroll

claytons
claytons2


screen shot 2017-09-26 at 12 48 21 pm
screen shot 2017-09-26 at 12 54 42 pm

**Comment by sg00dwin** [comment]
@smarterclayton I merged in your changes from https://github.com/openshift/test-infra/pull/31

[screenshot 1](https://user-images.githubusercontent.com/1874151/31148897-19ce4922-a85c-11e7-9da4-5432708899fb.png)

[screenshot 2](https://user-images.githubusercontent.com/1874151/31148898-1a1a8f4e-a85c-11e7-845f-59b04119cf75.png)

**Comment by smarterclayton** [comment]
Thanks steve

**Pull request merged**
